### ISSUE TITLE
Conflicts in config.json with multiple new exercises

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/xecmascript#102]
@kytrinyx whenever there is more than one pending PR for a new exercise, merging one creates a conflict in `config.json`.  Not a huge deal, but it does complicate splitting up the work of adding new exercises.

Is there a way to remove the dependency on `problems[]`, maybe by building the list dynamically from the directory names or putting a config.json file in each exercise directory?

**Comment by kytrinyx** [comment]
Could the exercises be added somewhere before the end of the list? It only gets conflicts if two exercises are added at the same position (e.g. the end of the list).

I don't want to build the list dynamically, because not all the directories are exercises. Also, some exercises get deprecated, but still have to be there in order for people to be able to restore their old work.

**Comment by matthewmorgan** [comment]
Yes, I could skip ahead and add the last exercise, then any added at that point would be not at the end of the list.  No one has gotten that far on the ES track yet anyway that I can see.

I don't really know how git detects a conflict-- I assumed it was by line number in the file.  If that's true, I think we would still have the same problem adding to the middle with concurrent unmerged branches modifying the same file.  BC the next added line will always be the same line number, right?  Until the list grows?

**Comment by kytrinyx** [comment]
No, git doesn't use line numbers. It doesn't use files at all, actually.

**Comment by matthewmorgan** [comment]
I did a little further reading, and it looks like the conflict results if "neighboring lines" are modified.  I think that adding the trailing comma on the old last exercise preceding each new exercise might be the source of the conflict.  Otherwise they're distinct new additions.

Worth a try?

**Comment by kytrinyx** [comment]
No, the source of the conflict is that both new exercises get added at the same location (neighboring line).

e.g.

```
# original
"problems": {
  "hello-world",
  "bob"
}

# PR 1
"problems": {
  "hello-world",
  "leap",
  "bob"
}

# PR 2
"problems": {
  "hello-world",
  "pangram",
  "bob"
}
```

The neighboring line is "hello-world", and both PRs want to put it in the same location. Git can't guess in this situation.

**Comment by matthewmorgan** [comment]
OK, so it sounds like any successive pending PRs need to have config.json edited in unique locations for this to work?  IE adding to the middle only works if you add to a different part of the middle for successive pending PRs?  Sorry to be dense...

**Comment by kytrinyx** [comment]
Yeah, that's how I understand it.

**Comment by rchavarria** [comment]
@matthewmorgan What if we take the last exercise of JavaScript track and port it to ECMAScript? Doing so, the last problem will no longer change (in a long period of time I hope), the one without the semicolon, and we're going to avoid conflicts.

Not sure if it would work.

**Comment by matthewmorgan** [comment]
@rchavarria, I don't think that will work.  If you have two branches checked out from master and add new exercises at the same line in `config.json` relative to master, merging the first one will cause a conflict in the second.

I just tested this on the CLI and it doesn't work.  It seems like that leaves us with a few options:
1) Never submit a PR to add a new exercise if there is already an unmerged PR for a different new exercise.  Seems counterproductive.
2) Add the new exercises at different places in the `config.json`.  I think the key is to add the subsequent new exercise in a place where it isn't adjacent to any lines that are adjacent to any other pending new exercise.  To extend @kytrinyx 's example:
```
# original
"problems": {
  "hello-world",
  "bob",
  "word-count",
  "leap"
}

# PR 1
"problems": {
  "hello-world",
  "new-exercise-1",
  "bob",
  "word-count",
  "leap"
}

# PR 2
"problems": {
  "hello-world",
  "bob",
  "word-count",
  "new-exercise-2",
  "leap"
}
```

If that's what we decide to do, we would need to periodically submit a PR to reorder `config.json` to sync with the JS track, as I did last night.
3) Continue using the method of #106.  I think this is OK for PRs that are branched from exercism/xecmascript, but won't work with outside forks.

I would vote for 2 or 3.  What do you think?

**Comment by rchavarria** [comment]
Let's go for number 2). It requires manual work from time to time, but it allows us to submit several exercises in a row.

I don't like number 1) at all.

**Comment by kytrinyx** [comment]
I think 2 sounds good as well. I often have a bunch of PRs lined up but only submit the first one, then as they're merged I rebase and fix any conflicts and push up the others one at a time, but 2 is still better than that :)

**Comment by matthewmorgan** [comment]
OK, thanks to both of you.  #2 sounds good to me!
