### ISSUE TITLE
Make it easier for an exercism user to run tests for an assignment

### ISSUE THREAD

**Issue by rchavarria** [exercism/xecmascript#12]
I struggled a little bit while running my code for the palindrome-products assignment, so I was wondering if there could be a better way to run them.

I was thinking of having a `package.json` file (as if the assignment was a NodeJS module) and a `gulpfile.js` file, to have all the work automated in a [Gulp](http://gulpjs.com) script.

But I'm not sure if this is compatible with exercism's philosophy. The exercism user must have installed NodeJS (I think this is acceptable) and she must first install `gulp-cli` tool so that she can run then the Gulp script. Then, for each assignment, the idea is that the user has just to run a `npm install` command at the beginning, and `npm test` or `gulp test` every time she wants to run her tests.

If this way of working on ecmascript assignments is ok, I'll implement it on the existing one, palindrome-products, and I'll make a pull request.

**Comment by kytrinyx** [comment]
I think that it would be fine to have gulp, as long as the version with fewer dependencies is documented, and gulp is a "nice to have". Anything to make it easier to get started is a good thing, I think.

**Comment by rchavarria** [comment]
Fixed with the old [Pull Request #13](https://github.com/exercism/xecmascript/pull/13)
