### ISSUE TITLE
Next submission acts strangely

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/xecmascript#176]
@kytrinyx I think when the 'next submission' button is clicked in the GUI, the user is supposed to see the next available submission of whatever solution they were viewing at the time, IE a different user's submission.

When I click this button, I instead get whatever solution I previously submitted, IE a solution to a different problem.  Then, sometimes, I get 404.

I'm guessing this is an issue with the exercism app itself?

**Comment by kytrinyx** [comment]
Probably, yes.

The behavior isn't quite what I want yet, but the "next" is supposed to depend on what filters you have on the http://exercism.io/inbox page.

See https://github.com/exercism/exercism.io/issues/2585

**Comment by matthewmorgan** [comment]
Looks like this feature has been removed from the UI, so I'm going to close this issue.
