### ISSUE TITLE
triangle: incorrect test in some tracks

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xecmascript#191]
Please check if there's a test that states that a triangle with sides 2, 4, 2 is invalid. The triangle inequality states that for any triangle, the sum of the lengths of any two sides must be greater than or equal to the length of the remaining side. If this doesn't affect this track, go ahead and just close the issue.

**Comment by matthewmorgan** [comment]
Tested and legal in this track.

**Comment by kytrinyx** [comment]
+1 thanks!
