### ISSUE TITLE
largest-series-product: Should tests test for implementation details (slices, digits)?

### ISSUE THREAD

**Issue by rchavarria** [exercism/xecmascript#202]
Address discussion on [x-common#192](https://github.com/exercism/x-common/issues/192).

Check if this language track tests implementation details. If so, try to include some hints as in an [Elixir exercise](https://github.com/exercism/xelixir/tree/master/exercises/zipper/hints).

**Comment by matthewmorgan** [comment]
@rchavarria I think this is OK.  This exercise is pretty straightforward and well explained in the README.

**Comment by rchavarria** [comment]
Yep, totally agree. I just saw this issue, the PR #203 and the PR on the xjavascript.

Nice, very great job!
