### ISSUE TITLE
Verify "Largest Series Product" exercise implementation

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xecmascript#204]
There was some confusion in this exercise due to the ambiguous use of the term _consecutive_ in the README. This could be taken to mean _contiguous_, as in consecutive by position, or as in _consecutive numerically_. The the README has been fixed (https://github.com/exercism/x-common/pull/200).

**Please verify that the exercise is implemented in this track correctly** (that it finds series of contiguous numbers, not series of numbers that follow each other consecutively).

If it helps, the canonical inputs/outputs for the exercise can be found here:
https://github.com/exercism/x-common/blob/master/largest-series-product.json

If everything is fine, go ahead and just close this issue. If there's something to be done, then please describe the steps needed in order to close the issue.

**Comment by rchavarria** [comment]
None of the tests included in this track violates rules stated in the `README`.

But, there are interesting cases in the canonical inputs/outputs that could be added:

```
[
// ...
    {
        "description": "can get the largest product of a big number (Project Euler)",
        "digits": "7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450",
        "span": 13,
        "expected": 23514624000
    },
    {
        "description": "reports zero if all spans include zero",
        "digits": "99099",
        "span": 3,
        "expected": 0
    },
    {
        "description": "rejects invalid character in digits",
        "digits": "1234a5",
        "span": 2,
        "expected": -1
    },
    {
        "description": "rejects negative span",
        "digits": "12345",
        "span": -1,
        "expected": -1
    }
]
```
And, one case that explains the weird (I found it weird the first time I read the specs) spec that returns `1` (the spec already exists, but not the explanation):

```
{
    "#": [
      "There may be some confusion about whether this should be 1 or error.",
      "The reasoning for it being 1 is this:",
      "There is one 0-character string contained in the empty string.",
      "That's the empty string itself.",
      "The empty product is 1 (the identity for multiplication).",
      "Therefore LSP('', 0) is 1.",
      "It's NOT the case that LSP('', 0) takes max of an empty list.",
      "So there is no error.",
      "Compare against LSP('123', 4):",
      "There are zero 4-character strings in '123'.",
      "So LSP('123', 4) really DOES take the max of an empty list.",
      "So LSP('123', 4) errors and LSP('', 0) does NOT."
    ],
    "description": "reports 1 for empty string and empty product (0 span)",
    "digits": "",
    "span": 0,
    "expected": 1
}
```

**Comment by matthewmorgan** [comment]
@rchavarria that last one is weird.  I thought it was in this track, but I must be remembering the java track.

**Comment by matthewmorgan** [comment]
@rchavarria are you proposing that we implement the 'interesting cases' you mentioned above?  Let me know,  is be happy to?

**Comment by rchavarria** [comment]
@matthewmorgan Yep, that cases are in the canonical inputs/outputs, but not on the track, so it would be nice to have them. Feel free to add them if you want.

**Comment by matthewmorgan** [comment]
OK I just tried to push this change, guessing GitHub is still having some issues.  Will try again soon.
