### ISSUE TITLE
Remove dependency on Babel

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/xecmascript#243]
Since version 4.0, NodeJS has supported most ES6 features out of the box.  Node is now 6.5, and according to [kangax](http://kangax.github.io/compat-table/es6/#node65), supports ES6 at 97%, where Babel is only at 71%.

Because all tests run in Node, it doesn't make any sense to transpile this code anymore.

@rchavarria Let's clean this up!

**Comment by rchavarria** [comment]
It would be great! I've heard that modules (functionality provided by the `export` and `import` keywords) is one key functionality that is not supported (at least) for browsers.

If all tests pass without transpiling in NodeJS v6.x I won't have any problem removing Babel. In fact, NodeJS version 6.x is going to be a long time support (LTS) very soon (18th October). So, it's a good time to start trusting version 6.x of NodeJS.

But it should be clear in the docs the minimum NodeJS version that is supported. And it would be great if we show a warning message if a user tries to solve an exercise with an older version.

It seems it's time for changes ;)

**Comment by matthewmorgan** [comment]
@rchavarria, I did some investigation and in fact you are right about the modules.  This is not a big deal, but it would require that all the exercises be refactored to use `require`, so that's a bit of work for sure.

There's gigantic jump in ES6 compatibility with node 6.8 according to this reference: http://node.green/ so if we were to switch I would say that is the version to use, otherwise even things like rest parameters are left out.

Maybe not worth the investment of time?

**Comment by rchavarria** [comment]
Hmmm, on one side, I'm lazy and I'd prefer to wait for ES6 modules to be supported. On the other hand, it's not clear that it will be implemented. And probably, `require` will still work for a long time.

I'm not sure yet, but I'd keep this track as it is. If we remove Babel, it'll be exactly as the JavaScript track (just with a newer version of NodeJS). Well, at some point in the future, both tracks will need to be *merged*. I don't know, what about deciding a deadline to wait until NodeJS supports (or not) ES6 modules? If the deadline is reached, and there is no support, we'll migrate everything to `require`. If there is support, we can remove Babel without fear.

**Comment by matthewmorgan** [comment]
I'm going to close this issue for now.
