### ISSUE TITLE
Verify contents and format of track documentation

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xecmascript#254]
Each language track has documentation in the `docs/` directory, which gets included on the site
on each track-specific set of pages under [/languages](http://exercism.io/languages).

We've added some general guidelines about how we'd like the track to be documented in exercism/exercism.io#3315
which can be found at https://github.com/exercism/exercism.io/blob/master/docs/writing-track-documentation.md

Please take a moment to look through the documentation about documentation, and make sure that
the track is following these guidelines. Pay particularly close attention to **how to use images**
in the markdown files.

Lastly, if you find that the guidelines are confusing or missing important details, then a pull request
would be greatly appreciated.

**Comment by rchavarria** [comment]
This track has all those files, and they explain what they are supposed to explain. But some content could be improved, if we feel like it.

For example, `INSTALLATION.md` recommends to install the `gulp-cli` tool (used to run tests), but now tests can be executed with `npm test` (or `npm lint test`). So, it could be simplified. And `TESTS.md` content updated with those new ways of running tests.

And it'd be nice to include more links on `LEARNING.md` or `RESOURCES.md`.

Anyway, I'd like other @exercism/javascript people to take a look a these files.
