### ISSUE TITLE
Update infrastructure to use NodeJS 6+, `latest` babel presets

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/xecmascript#267]
@exercism/javascript We are using somewhat older versions of Node and Babel.  I was going to suggest to a contributor that he update his solution to incorporate generators, but he wouldn't have been able to do that without an update on our end.

Any concerns?  If not, let's make it happen!

**Comment by rchavarria** [comment]
I'm have my doubts about updating Node version in xjavascript, but this track is supposed to be at the edge of the JavaScript specs. So, yeah, this track should update Node and Babel versions.

I think I can work on this issue this week, but I don't mind if anybody wants to take care of this.

**Comment by matthewmorgan** [comment]
@rchavarria I decided to take a crack at this.  Nearly done...
