### ISSUE TITLE
Need a Gitter room

### ISSUE THREAD

**Issue by tejasbubane** [exercism/xecmascript#275]
We need a gitter room for `javascript`. We can have a combined room for `javascript` and `ecmascript` since the users are mostly same.

After a chat on `exercism/dev` channel in `gitter`, I was suggested to open an issue and any of the maintainers would be able to create the channel. Hence the issue.

PS: After creating the channel we should add a badge to the README.

**Comment by matthewmorgan** [comment]
@tejasbubane @rchavarria I think we need someone with more clout on the exercism github realm.  @kytrinyx ?

**Comment by joelwallis** [comment]
We definitely need a Gitter room! 🙌

**Comment by kotp** [comment]
@exercism/javascript team members have been pinged, they should be able to create one for here.

**Comment by matthewmorgan** [comment]
@tejasbubane @joelwallis @kotp I think this is a paid service beyond the first room, and @jtigger of xjava beat us to it.  Unless you know something about Gitter that I don't...

I have created a free room call `exercism-xecmascript` that you should be able to find by searching.  I `@`-mentioned you all, and a couple of other folks as well.

**Comment by kotp** [comment]
I am not finding the room `exercism-xecmascript` but I do see that the proper room is now created.  Did you remove the one that you mentioned here?

**Comment by matthewmorgan** [comment]
@kotp yes, sorry.  That was me scrambling to get it created before leaving for work.  We're in business now.

**Comment by kotp** [comment]
OK, let's edit your message to not direct people there in your comment, line it out or indicate that it was removed?

**Comment by kotp** [comment]
Thank you @matthewmorgan for doing that, it will keep others from taking the time to search for it as I did.

**Comment by matthewmorgan** [comment]
That was a good catch.  Thank _you_!
