### ISSUE TITLE
Clarify docs on node installation vs 'npm install'

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/xecmascript#284]
Just now, looking at the [README](https://github.com/exercism/xecmascript/blob/master/README.md), the wording is unclear.  It might very well look as if typing 'npm install' is the command to install NodeJS itself, when actually it is the command to install the project dependencies, and should be run _after_ installing node on your machine.

<img width="977" alt="screen shot 2017-05-09 at 5 58 27 pm" src="https://cloud.githubusercontent.com/assets/2478531/25874617/4dd26436-34e1-11e7-9c1e-b030380a2b7d.png">

Success Criteria:
- the wording is expanded to show that installing NodeJS is the first step
- it is clearly explained that running `npm install` is for installing dependencies locally

**Comment by tejasbubane** [comment]
Good catch!

While we are at it, I found `Javascript` in the readme which should be replaced by `Ecmascript`:

![screen shot 2017-05-10 at 10 48 29 am](https://cloud.githubusercontent.com/assets/980783/25884200/45e07ea6-356e-11e7-94ed-17704df5fbe0.png)

**Comment by tejasbubane** [comment]
Sorry for grabbing a `first patch` issue, but there were so many small things to fix in the README that it was difficult to put them in an issue. So I went ahead and did the changes.

**Comment by matthewmorgan** [comment]
@tejasbubane I think one thing we could do is work on identifying some issues that could be tackled at different levels.  I think it's nice to keep some 'good first patch' issues open as a welcoming entry point for new contributors.

No worries about fixing this one at all.
