### ISSUE TITLE
Improvements to `test-package-files`

### ISSUE THREAD

**Issue by tejasbubane** [exercism/xecmascript#301]
* **Checks for package.json in `node_modules` as well.**

`test-package-files` task from Makefile checks for [all package.json from exercises and its subdirectories](https://github.com/exercism/xecmascript/blob/master/Makefile#L16) which also includes any `node_modules` inside. eg. `exercises/phone-number/node_modules/{some-package}/package.json`. This is usually not the case, but happened with me since I had created the phone-number exercise and had tested in the same directory. The task fails since these file obviously don't match.

* **Error does not show filename.**

Filename which does not match would be helpful here
```
⇒  make test
make[1]: *** [test-package-files] Error 1
make: *** [test] Error 2
```

Action items:

- [x] Show filenames in error msg for `test-package-files`.
- [x] Ignore `node_modules` inside exercises.

**Comment by matthewmorgan** [comment]
@tejasbubane I am wondering if this is why @arthurchipdean's alphametics PR is not building( #299 ) .

If you're planning on working on this, great, otherwise I may fix it later to move things along.  Let me know.  Thanks!

**Comment by tejasbubane** [comment]
> I am wondering if this is why @arthurchipdean's alphametics PR is not building( #299 )

Nope that is a genuine error. `package.json` for `alphametics` has been change but the change is not propagated over to other files. My scenario won't happen on travis since there will be no `node_modules` inside `exercises` directory. Can happen on local if you run test on single exercise using `yarn install && yarn test`.

I am working on fixing this.

Action items:
- [ ] Show filenames in error msg for `test-package-files`.
- [ ] Ignore `node_modules` inside exercises.

**Comment by matthewmorgan** [comment]
@tejasbubane if you just add the `-maxdepth=1` parameter to the `find` command I think you can ignore the nested `package.json` files.  I just tried it and it worked for me.

Good luck!

**Comment by tejasbubane** [comment]
Thanks @matthewmorgan That totally worked!
