### ISSUE TITLE
Code submissions have no syntax highlighting

### ISSUE THREAD

**Issue by rchavarria** [exercism/xecmascript#34]
When I review code submissions in exercism.io I miss some syntax highlighting. Is this something that can be fixed in the language track? 

Just highlighting it just as JavaScript code would be the fastest fix and maybe enough for now.

![no-syntax-highlight](https://cloud.githubusercontent.com/assets/612688/10435724/edeb0f02-7121-11e5-8c36-3e76593ed685.png)

Additionally, next to the submission title, there is a yellow circle. In the JavaScript language track it shows a "JS" text. Could it show some text for ECMAScript? "ES" or other customized icon?

**Comment by kytrinyx** [comment]
Yepp, the highlighting thing can be fixed with one line somewhere (let me figure out where that was).

Also, I can't remember how the JS thing happened. I'll look into that as well.

**Comment by kytrinyx** [comment]
If you add an image at `lib/app/public/img/ecmascript.png` then you'll get an icon on the code page.

**Comment by rchavarria** [comment]
Ok. Now it's time for the difficult part. Finding a representative image.

Thanks for fixing the syntax.

**Comment by kytrinyx** [comment]
yepp :)

**Comment by rchavarria** [comment]
Sorry to reopen this issue @kytrinyx, but exercism.io does not highlight the ECMAScript syntax anymore. 

I don't find the code that fixed it in the past in the current source code, and I don't know where to look for. Sorry, I can't help.

**Comment by kytrinyx** [comment]
Ah, no problem. We had a fix recently to some of the syntax highlighting that must have wiped out the fix. I'll find it and fix it today (should be easy).

**Comment by rchavarria** [comment]
Awesome! Thanks!

**Comment by kytrinyx** [comment]
Found it. We wrote the code to make sure that we got the syntax highlighting... and then forgot to call it. :)

**Comment by rchavarria** [comment]
Hilarious! BTW, thanks for the fix
