### ISSUE TITLE
Which library should be used to transpile ECMAScript 2015 code to ECMAScript 5

### ISSUE THREAD

**Issue by rchavarria** [exercism/xecmascript#37]
There are several libraries/platforms that support ECMAScript 2015, but they don't cover all the features. Options are:

- NodeJS v4, that covers 51%
- Babel, that covers 79%
- Traceur, that covers 59%. This is what the language track currently uses.

Babel seems the best option.

@kytrinyx, how could more people be involved on this discussion?

**Comment by kytrinyx** [comment]
I tweeted about it here: https://twitter.com/exercism_io/status/654661701799837700

**Comment by locks** [comment]
I would vote on Babel. Ember CLI uses Babel for its compiling needs, and React also moved to Babel for JSX compiling.

How did you arrive at the percentages @rchavarria ?

**Comment by wpannell** [comment]
Much current practice, particularly around Facebook React, recommends Babel, e.g., [here](https://github.com/ericelliott/tdd-es6-react/tree/master/examples) and [here](http://teropa.info/blog/2015/09/10/full-stack-redux-tutorial.html#project-setup).

**Comment by poteto** [comment]
Out of all the available transpilers, Babel has the highest % of feature parity with ECMA2015. See https://kangax.github.io/compat-table/es6/ for a nice little table.

**Comment by grapho** [comment]
I'll vote Babel!

**Comment by miguelcobain** [comment]
Babel is the way to go.

**Comment by kentcdodds** [comment]
Definitely recommend Babel. Many people are used to Babel (it's the most popular by far).

As a side, it would probably be good to add typescript support as well...

**Comment by joshburgess** [comment]
Babel.

**Comment by adrianhall** [comment]
Yep - Babel.  Babel is also easy to integrate with build systems like Grunt and Gulp.

**Comment by elwayman02** [comment]
:+1: Babel

**Comment by rchavarria** [comment]
@locks I arrived at those percentages in a conversation with a friend of mine. I have no data to confirm them. But @poteto's link is a wonderful resource and it shows close percentages. Babel has one of the highest coverage.

**Comment by rchavarria** [comment]
The replacement will be addressed by Issue #51
