### ISSUE TITLE
Create a getting started page in the docs repository

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xecmascript#5]
See http://help.exercism.io/getting-started-with-go.html as an example.

If appropriate, suggest a linter (see exercism/docs#54).

**Comment by rchavarria** [comment]
Getting started page added on [exercism/docs PR#151](https://github.com/exercism/docs/pull/151) and updated on [exercism/docs PR#171](https://github.com/exercism/docs/pull/171).

Issue #44 will track whether a linter is added to the project, so this issue could be closed.

**Comment by kytrinyx** [comment]
Good call.
