### ISSUE TITLE
Update language track description re: babel vs traceur

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/xecmascript#82]
The user-facing description of the language track still refers to Traceur:

http://help.exercism.io/getting-started-with-ecmascript.html

We should update that.  Where does the helpfile live?

**Comment by kytrinyx** [comment]
it's in the https://github.com/exercism/docs repo... but I'm not able to deploy it at the moment because I'm getting a node error that makes no sense.

**Comment by matthewmorgan** [comment]
@kytrinyx let me know when it's working.  I can work with @rchavarria on making appropriate edits.  Thanks!

**Comment by kytrinyx** [comment]
Will do.

**Comment by matthewmorgan** [comment]
@rchavarria it looks to me like it's just a matter of changing the three references to Traceur, along with the hyperlinks.  Am I missing anything?

**Comment by kytrinyx** [comment]
I'm going to move all of the documentation over to the language-specific repositories today and serve it from the problems api: https://github.com/exercism/exercism.io/pull/2628

I'll be getting rid of the help.exercism.io app altogether.

**Comment by rchavarria** [comment]
@matthewmorgan We could wait until @kytrinyx moves the documentation. And yep, you're right, we should update the doc and point to Babel instead of Traceur. It's just a matter of links, and it doesn't affect to exercises code.

**Comment by kytrinyx** [comment]
I'm going to work on the documentation today, and since it will be in your own repository after that it will be much, much easier to fix!

**Comment by kytrinyx** [comment]
Fixed in #89
