### ISSUE TITLE
Figure out a way to remove duplication between main and individual exercises `gulpfile.js`

### ISSUE THREAD

**Issue by rchavarria** [exercism/xecmascript#83]
Currently, the main `gulpfile.js` file is just copied into each individual exercise when running the `make` command at development time. Keeping them synchronized by copying is not the best way to remove duplication.

Figure out a better way to share code between all `gulpfile.js` files and remove duplication.

**Comment by matthewmorgan** [comment]
This issue could be closed were #277 merged.
